
target-version = "py312"
line-length = 120

[lint]
select = ["ALL"]

ignore = [
    #### modules
    "ANN", # flake8-annotations
    "COM", # flake8-commas
    #"C90", # mccabe complexity
    "DJ",  # django
    "EXE", # flake8-executable
    "T10", # debugger
    
    ## Specific rules
    "D100",   # ignore missing docs
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D205",
    "D212",
    "D400",
    "D401",
    "D415",
    "TRY003", # external messages in exceptions are too verbose
    "TD002",
    "TD003",
    "FIX002", # too verbose descriptions of todos
    "TC001",

    "ISC001", # Conflicts with formatter
    "D203", # Conflicts with another rule
    ]